version: '3.8'

services:
  sip-lifecycle-agent:
    # Build the image from the included Dockerfile
    build:
      context: .
    image: sip-lifecycle-agent:latest
    restart: unless-stopped

    # This app connects out to LiveKit and other services; no inbound ports needed
    # If you later need inbound webhooks, add `ports:` here.

    # Environment variables are injected directly by Coolify.
    # Add the following variables to your Coolify service configuration.
    environment:
      - PYTHONUNBUFFERED=1
      - LIVEKIT_URL=${LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - CARTESIA_API_KEY=${CARTESIA_API_KEY}

    # Override the Dockerfile CMD to run the SIP lifecycle agent
    command: ["uv", "run", "python", "src/sip_lifecycle_dtmf.py", "dev"]

    # Persist logs if you want to keep them between deployments (optional)
    # volumes:
    #   - agent_logs:/app/llm_logs
    #   - agent_debug:/app/agent_debug.log

# volumes:
#   agent_logs:
#   agent_debug:
